### ISSUE TITLE
Z-Index Use

### ISSUE THREAD

**Issue by jim-rosales** [narokoe/prj-rev-bwfs-tea-cozy#4]
I'm not sure if this was intended but currently with the z-index at three the location hides the navigation bar as shown below:
<img width="1211" alt="screen shot 2018-02-21 at 9 16 17 am" src="https://user-images.githubusercontent.com/28379087/36495040-ce0e2100-16e8-11e8-90fe-4a7910d5bf29.png">

If you remove this z-index the text will flow behind the navigation bar
<img width="1049" alt="screen shot 2018-02-21 at 9 23 14 am" src="https://user-images.githubusercontent.com/28379087/36495071-ebd6df24-16e8-11e8-8b0e-e452b3389687.png">

https://github.com/narokoe/prj-rev-bwfs-tea-cozy/blob/02b8ae525eaefa029ce8611c3dca61d55b0b950b/Tea%20Cozy/Resources/css/style.css#L144

**Comment by narokoe** [comment]
I did not catch that, that was definitely a mistake.   Thank you.
So I should have bumped up the z-index for the nav bar to fix that in this instance?

**Comment by jim-rosales** [comment]
You don't need to increase the z-index for the nav bar just simply remove the z-index in this rule.
For example for this section the resulting rule would be:
```CSS
.location-image-content {
  background-color: black;
  display: inline-flex;
  flex-direction: row;
  text-align: center;
  justify-content: center;
  align-items: center;
  position: relative;
  height: 300px;
  width: 300px;
  /** z-index: 3; **/
  margin-top: 150px;
  margin-bottom: 150px;
  margin-right: 20px;
  margin-left: 20px;
}
```
